cuda:
  # renovate: datasource=custom.nvidia-driver depName=nvidia-cuda-driver versioning=loose
  version: "565.57.01"

grid:
  # renovate: datasource=custom.nvidia-grid depName=nvidia-grid-driver versioning=loose
  version: "530.150.01"
  url: "https://download.microsoft.com/download/8/d/a/8da4fb8e-3a9b-4e6a-bc9a-72ff64d7a13c/NVIDIA-Linux-x86_64-535.161.08-grid-azure.run"
