cuda:
  # renovate: datasource=custom.nvidia-driver depName=nvidia-cuda-driver versioning=loose
  version: "530.00.00"

grid:
  # renovate: datasource=custom.nvidia-grid-driver depName=nvidia-grid-driver versioning=loose
  version: "535.161"
  url: "https://download.microsoft.com/download/8/d/a/fsdfsdfds-3a9b-4e6a-bc9a-72ff64ddsfsc/NVIDIA-Linux-x86_64-535.161-grid-azure.run"
